// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T;
  interface InternalApi {
    "/__nuxt_error": {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import("../../node_modules/.pnpm/@nuxt+nitro-server@3.21.9_dc4e27089aba977b69054268c9e5ac6e/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer").default
            >
          >
        >
      >;
    };
    "/__nuxt_island/**": {
      default: Simplify<
        Serialize<
          Awaited<
            ReturnType<
              typeof import("../../server/#internal/nuxt/island-renderer").default
            >
          >
        >
      >;
    };
  }
}
export {};
