name: OSV-Scanner

on:
  pull_request:
    branches: ["develop"]
  merge_group:
    branches: ["develop"]
  schedule:
    - cron: "26 14 * * 5"
  push:
    branches: ["develop"]

permissions:
  security-events: write
  contents: read

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run OSV-Scanner
        uses: google/osv-scanner-action/osv-scanner-cli@v2.3.8
        with:
          scan-args: |-
            -r
            --skip-git
            ./

  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.3.8"
    with:
      scan-args: |-
        -r
        --skip-git
        ./
